# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          # Action to perform
          action: ''
          # Directory location of the application source code
          app_location: ''
          # Required token
          azure_static_web_apps_api_token: ''
          # Custom command for Oryx to run when building Azure Functions source code
          api_build_command: '' # optional
          # Directory location of the Azure Functions source code
          api_location: '' # optional
          # Directory location of the compiled application code after building
          app_artifact_location: '' # optional
          # Custom command for Oryx to run when building application source code
          app_build_command: '' # optional
          # Token for interacting with the Github repository. Currently used only for commenting on Pull Requests.
          repo_token: '' # optional
          # Directory location where the routes.json file can be found in the source code
          routes_location: '' # optional
